<?xml version="1.0"?>
<package format="3">
  <name>a300_bringup</name><version>0.2.0</version>
  <description>A300 system bringup.</description>
  <maintainer email="dev@a300.local">A300 Development</maintainer><license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>a300_obstacle_avoidance</exec_depend><exec_depend>a300_joystick</exec_depend><exec_depend>a300_lidar</exec_depend><exec_depend>a300_gazebo</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
